import PDFDocument from "pdfkit";
import type { ScreeningResult } from "../types";

interface JobLike { title: string }
interface ExplanationCandidate {
  candidateId: string;
  candidateName: string;
  rank: number;
  totalScore: number;
  transparencyScore: number;
  strengths: string[];
  gaps: string[];
  recommendation: string;
  mustHaveSkillsMet: string[];
  mustHaveSkillsMissing: string[];
  estimatedOnboardingTime: string;
  aiConfidenceScore: number;
}

interface ExplanationRejectedCandidate {
  candidateId: string;
  candidateName: string;
  whyNotShortlisted: string[];
}

interface ExplanationsPayload {
  screeningId: string;
  jobId: string;
  jobTitle: string;
  shortlistExplanations: ExplanationCandidate[];
  rejectedCandidateInsights: ExplanationRejectedCandidate[];
  generatedAt: string;
}

export const generateShortlistPDF = async (screening: ScreeningResult, job: JobLike): Promise<Buffer> => {
  return new Promise((resolve) => {
    const doc = new PDFDocument({ margin: 40 });
    const chunks: Buffer[] = [];
    doc.on("data", (chunk) => chunks.push(chunk as Buffer));
    doc.on("end", () => resolve(Buffer.concat(chunks)));

    doc.fontSize(18).text("Umurava AI HR - Shortlist Report");
    doc.moveDown();
    doc.fontSize(12).text(`Job: ${job.title}`);
    doc.text(`Total analyzed: ${screening.totalAnalyzed}`);
    doc.text(`Average score: ${screening.averageScore}`);
    doc.moveDown();

    screening.shortlist.forEach((c) => {
      doc.fontSize(13).text(`#${c.rank} Candidate ${c.candidateId} - ${c.totalScore}`);
      doc.fontSize(10).text(`Breakdown: Skills ${c.breakdown.skillsMatch} | Exp ${c.breakdown.experienceMatch} | Edu ${c.breakdown.educationMatch} | Fit ${c.breakdown.culturalFit}`);
      doc.text(`Must-have met: ${c.mustHaveSkillsMet.join(", ") || "N/A"}`);
      doc.text(`Missing: ${c.mustHaveSkillsMissing.join(", ") || "None"}`);
      doc.text(`Onboarding: ${c.estimatedOnboardingTime} | Confidence: ${c.aiConfidenceScore}`);
      doc.text(`Recommendation: ${c.recommendation}`);
      doc.moveDown();
    });

    doc.fontSize(9).text("Generated by Umurava AI HR — Human review required");
    doc.end();
  });
};

export const generateExplanationsPDF = async (payload: ExplanationsPayload): Promise<Buffer> => {
  return new Promise((resolve) => {
    const doc = new PDFDocument({ margin: 40 });
    const chunks: Buffer[] = [];
    doc.on("data", (chunk) => chunks.push(chunk as Buffer));
    doc.on("end", () => resolve(Buffer.concat(chunks)));

    doc.fontSize(18).text("Umurava AI HR - Judge Ready Explanation Report");
    doc.moveDown(0.5);
    doc.fontSize(11).text(`Screening ID: ${payload.screeningId}`);
    doc.text(`Job: ${payload.jobTitle}`);
    doc.text(`Generated At: ${payload.generatedAt}`);
    doc.moveDown();

    doc.fontSize(14).text("Shortlist Explanations");
    doc.moveDown(0.5);
    payload.shortlistExplanations.forEach((candidate) => {
      doc.fontSize(12).text(
        `#${candidate.rank} ${candidate.candidateName} (${candidate.candidateId}) - Score ${candidate.totalScore}/100`,
      );
      doc.fontSize(10).text(`Transparency Score: ${candidate.transparencyScore}/100`);
      doc.text(`AI Confidence: ${candidate.aiConfidenceScore}/100`);
      doc.text(`Onboarding Estimate: ${candidate.estimatedOnboardingTime}`);
      doc.text(`Must-Have Skills Met: ${candidate.mustHaveSkillsMet.join(", ") || "None"}`);
      doc.text(`Missing Must-Have Skills: ${candidate.mustHaveSkillsMissing.join(", ") || "None"}`);
      doc.text(`Strengths: ${candidate.strengths.join(" | ")}`);
      doc.text(`Gaps/Risks: ${candidate.gaps.join(" | ")}`);
      doc.text(`Recommendation: ${candidate.recommendation}`);
      doc.moveDown();
    });

    doc.fontSize(14).text("Rejected Candidate Insights");
    doc.moveDown(0.5);
    payload.rejectedCandidateInsights.forEach((candidate) => {
      doc.fontSize(11).text(`${candidate.candidateName} (${candidate.candidateId})`);
      doc.fontSize(10).text(`Why not shortlisted: ${candidate.whyNotShortlisted.join(" | ")}`);
      doc.moveDown(0.5);
    });

    doc
      .fontSize(9)
      .text("Generated by Umurava AI HR. AI supports decisions; final hiring must remain human-led.");
    doc.end();
  });
};
