import type { TalentProfile } from "../types";

/** Profiles without DB id — assigned at seed time. */
export type TalentSeedProfile = Omit<TalentProfile, "id">;

const LOC = ["Kigali, Rwanda", "Nairobi, Kenya", "Lagos, Nigeria", "Accra, Ghana", "Cairo, Egypt", "Cape Town, South Africa"] as const;
const pick = (i: number) => LOC[i % LOC.length];

const av = (): TalentSeedProfile["availability"] => ({ status: "Available", type: "Full-time" });

const sk = (
  rows: Array<{ name: string; level: TalentProfile["skills"][number]["level"]; years: number }>,
): TalentProfile["skills"] => rows.map((r) => ({ name: r.name, level: r.level, yearsOfExperience: r.years }));

const ex = (
  rows: Array<{
    company: string;
    role: string;
    start: string;
    end: string;
    desc: string;
    tech: string[];
    current: boolean;
  }>,
): TalentProfile["experience"] =>
  rows.map((r) => ({
    company: r.company,
    role: r.role,
    startDate: r.start,
    endDate: r.end,
    description: r.desc,
    technologies: r.tech,
    isCurrent: r.current,
  }));

const edu = (inst: string, degree: string, field: string, sy: number, ey: number): TalentProfile["education"] => [
  { institution: inst, degree, fieldOfStudy: field, startYear: sy, endYear: ey },
];

/** 5 senior (8+ yrs) — expect strong scores */
export const seniorSeeds = (): TalentSeedProfile[] =>
  [
    {
      firstName: "Jean-Paul",
      lastName: "Nkusi",
      email: "jp.nkusi.umurava.seed@test.local",
      headline: "Staff Backend Engineer — Node.js / TypeScript / PostgreSQL",
      bio: "10+ years designing APIs and data layers for high-scale SaaS; owned incident response and hiring loops.",
      location: pick(0),
      skills: sk([
        { name: "TypeScript", level: "Expert", years: 9 },
        { name: "Node.js", level: "Expert", years: 10 },
        { name: "PostgreSQL", level: "Expert", years: 8 },
        { name: "MongoDB", level: "Advanced", years: 6 },
        { name: "Docker", level: "Advanced", years: 7 },
        { name: "AWS", level: "Advanced", years: 6 },
      ]),
      languages: [
        { name: "English", proficiency: "Fluent" },
        { name: "Kinyarwanda", proficiency: "Native" },
      ],
      experience: ex([
        {
          company: "Umurava Cloud",
          role: "Staff Engineer",
          start: "2018-03",
          end: "Present",
          desc: "Core payments API, Postgres sharding, CI/CD on AWS.",
          tech: ["TypeScript", "Node.js", "PostgreSQL", "Docker", "AWS", "CI/CD"],
          current: true,
        },
        {
          company: "East Africa FinTech",
          role: "Senior Backend Developer",
          start: "2014-01",
          end: "2018-02",
          desc: "Microservices, Kafka, MongoDB operational store.",
          tech: ["Node.js", "MongoDB", "Kafka", "Docker"],
          current: false,
        },
      ]),
      education: edu("University of Rwanda", "MSc", "Computer Science", 2012, 2014),
      certifications: [{ name: "AWS Solutions Architect Professional", issuer: "AWS", issueDate: "2021-06" }],
      projects: [
        {
          name: "LedgerSync",
          description: "Open-source reconciliation toolkit used by 3 regional banks.",
          technologies: ["TypeScript", "PostgreSQL", "Docker"],
          role: "Maintainer",
          link: "https://github.com/example/ledgersync",
          startDate: "2020-01",
          endDate: "Present",
        },
      ],
      availability: av(),
      socialLinks: { linkedin: "https://linkedin.com/in/example-nkusi", github: "https://github.com/jpnkusi" },
    },
    {
      firstName: "Amara",
      lastName: "Okafor",
      email: "amara.okafor.umurava.seed@test.local",
      headline: "Principal Frontend Engineer — React / Next.js / Design Systems",
      bio: "Led design-system adoption across web and mobile web; performance budgets and Core Web Vitals.",
      location: pick(1),
      skills: sk([
        { name: "React", level: "Expert", years: 9 },
        { name: "Next.js", level: "Expert", years: 7 },
        { name: "TypeScript", level: "Expert", years: 8 },
        { name: "TailwindCSS", level: "Advanced", years: 5 },
        { name: "Vue.js", level: "Advanced", years: 4 },
      ]),
      languages: [{ name: "English", proficiency: "Fluent" }],
      experience: ex([
        {
          company: "Savanna UI Labs",
          role: "Principal Engineer",
          start: "2019-06",
          end: "Present",
          desc: "Next.js app router migration, edge caching, component library.",
          tech: ["React", "Next.js", "TypeScript", "TailwindCSS"],
          current: true,
        },
        {
          company: "Lagos Commerce",
          role: "Senior Frontend Developer",
          start: "2015-04",
          end: "2019-05",
          desc: "SPA migration, webpack performance.",
          tech: ["React", "JavaScript", "CSS"],
          current: false,
        },
      ]),
      education: edu("University of Lagos", "BSc", "Computer Science", 2010, 2014),
      projects: [
        {
          name: "A11y Kit",
          description: "Accessible component primitives for internal products.",
          technologies: ["React", "TypeScript"],
          role: "Creator",
          link: "https://example.com/a11y-kit",
          startDate: "2021-03",
          endDate: "2024-12",
        },
      ],
      availability: av(),
      socialLinks: { portfolio: "https://amara-design.example.com", github: "https://github.com/aokafor" },
    },
    {
      firstName: "David",
      lastName: "Mwangi",
      email: "david.mwangi.umurava.seed@test.local",
      headline: "Tech Lead — Python / Django / PostgreSQL / GCP",
      bio: "8 years shipping B2B APIs; security reviews and mentoring.",
      location: pick(2),
      skills: sk([
        { name: "Python", level: "Expert", years: 9 },
        { name: "PostgreSQL", level: "Expert", years: 8 },
        { name: "MongoDB", level: "Advanced", years: 5 },
        { name: "Docker", level: "Advanced", years: 7 },
        { name: "GCP", level: "Advanced", years: 5 },
      ]),
      languages: [{ name: "English", proficiency: "Fluent" }, { name: "Swahili", proficiency: "Conversational" }],
      experience: ex([
        {
          company: "Nairobi DataWorks",
          role: "Engineering Lead",
          start: "2017-02",
          end: "Present",
          desc: "API platform on GCP Cloud Run, Postgres, CI/CD.",
          tech: ["Python", "PostgreSQL", "GCP", "Docker", "CI/CD"],
          current: true,
        },
        {
          company: "PanAfrika SaaS",
          role: "Senior Backend Engineer",
          start: "2014-01",
          end: "2017-01",
          desc: "REST + batch ETL jobs.",
          tech: ["Python", "PostgreSQL", "MongoDB"],
          current: false,
        },
      ]),
      education: edu("Strathmore University", "BSc", "Informatics", 2010, 2014),
      certifications: [{ name: "Professional Cloud Architect", issuer: "Google Cloud", issueDate: "2022-04" }],
      projects: [],
      availability: av(),
      socialLinks: { linkedin: "https://linkedin.com/in/dmwangi" },
    },
    {
      firstName: "Yasmine",
      lastName: "El-Sayed",
      email: "yasmine.elsayed.umurava.seed@test.local",
      headline: "ML Engineer — PyTorch / LangChain / Gemini API",
      bio: "Research-to-production ML; RAG pipelines and evaluation harnesses.",
      location: pick(4),
      skills: sk([
        { name: "Python", level: "Expert", years: 8 },
        { name: "PyTorch", level: "Expert", years: 6 },
        { name: "TensorFlow", level: "Advanced", years: 5 },
        { name: "LangChain", level: "Advanced", years: 3 },
        { name: "Gemini API", level: "Advanced", years: 2 },
      ]),
      languages: [{ name: "English", proficiency: "Fluent" }, { name: "Arabic", proficiency: "Native" }],
      experience: ex([
        {
          company: "Cairo AI Lab",
          role: "Senior ML Engineer",
          start: "2019-04",
          end: "Present",
          desc: "Fine-tuning, retrieval, Gemini-based assistants.",
          tech: ["Python", "PyTorch", "LangChain", "Gemini API"],
          current: true,
        },
        {
          company: "MENA Analytics",
          role: "ML Engineer",
          start: "2016-07",
          end: "2019-03",
          desc: "Computer vision pipelines.",
          tech: ["Python", "TensorFlow"],
          current: false,
        },
      ]),
      education: edu("Cairo University", "MSc", "Computer Engineering", 2014, 2016),
      projects: [
        {
          name: "RAGBench",
          description: "Benchmark suite for retrieval quality.",
          technologies: ["Python", "LangChain"],
          role: "Owner",
          startDate: "2023-01",
          endDate: "Present",
        },
      ],
      availability: av(),
      socialLinks: { github: "https://github.com/yelsayed" },
    },
    {
      firstName: "Thabo",
      lastName: "Dlamini",
      email: "thabo.dlamini.umurava.seed@test.local",
      headline: "DevOps Lead — Kubernetes / AWS / CI/CD",
      bio: "9 years running production platforms; SRE practices and cost optimization.",
      location: pick(5),
      skills: sk([
        { name: "Docker", level: "Expert", years: 9 },
        { name: "AWS", level: "Expert", years: 8 },
        { name: "CI/CD", level: "Expert", years: 9 },
        { name: "GCP", level: "Advanced", years: 4 },
      ]),
      languages: [{ name: "English", proficiency: "Fluent" }],
      experience: ex([
        {
          company: "Cape Scale Ops",
          role: "Head of Platform",
          start: "2018-01",
          end: "Present",
          desc: "EKS clusters, GitOps, incident tooling.",
          tech: ["Kubernetes", "AWS", "Docker", "CI/CD"],
          current: true,
        },
        {
          company: "Atlantic Hosting",
          role: "Senior DevOps Engineer",
          start: "2014-06",
          end: "2017-12",
          desc: "Bare-metal to cloud migration.",
          tech: ["AWS", "Docker", "CI/CD"],
          current: false,
        },
      ]),
      education: edu("University of Cape Town", "BSc", "Computer Science", 2010, 2013),
      certifications: [{ name: "CKA", issuer: "CNCF", issueDate: "2020-09" }],
      projects: [],
      availability: av(),
      socialLinks: { linkedin: "https://linkedin.com/in/tdlamini" },
    },
  ];

/** 7 mid-level (3–7 yrs) */
export const midSeeds = (): TalentSeedProfile[] =>
  [
    {
      firstName: "Kemi",
      lastName: "Adeyemi",
      email: "kemi.adeyemi.umurava.seed@test.local",
      headline: "Full-Stack Engineer — React / Node.js / MongoDB",
      bio: "Product-minded engineer shipping features end-to-end.",
      location: pick(2),
      skills: sk([
        { name: "React", level: "Advanced", years: 5 },
        { name: "Node.js", level: "Advanced", years: 5 },
        { name: "MongoDB", level: "Advanced", years: 4 },
        { name: "TypeScript", level: "Advanced", years: 4 },
      ]),
      languages: [{ name: "English", proficiency: "Fluent" }],
      experience: ex([
        {
          company: "Lagos Growth Co",
          role: "Software Engineer",
          start: "2021-03",
          end: "Present",
          desc: "Next.js dashboards + Node APIs.",
          tech: ["React", "Node.js", "MongoDB", "TypeScript"],
          current: true,
        },
        {
          company: "Startup Weekend Ltd",
          role: "Junior Developer",
          start: "2019-01",
          end: "2021-02",
          desc: "CRUD apps and integrations.",
          tech: ["JavaScript", "MongoDB"],
          current: false,
        },
      ]),
      education: edu("University of Lagos", "BSc", "Computer Science", 2015, 2019),
      projects: [
        {
          name: "Billing Portal",
          description: "Self-serve invoices for SMBs.",
          technologies: ["React", "Node.js"],
          role: "Full-stack",
          startDate: "2022-06",
          endDate: "2023-12",
        },
      ],
      availability: av(),
      socialLinks: { github: "https://github.com/kadeyemi" },
    },
    {
      firstName: "Peter",
      lastName: "Mutesi",
      email: "peter.mutesi.umurava.seed@test.local",
      headline: "Backend Developer — Python / FastAPI / PostgreSQL",
      location: pick(0),
      bio: "API design and Postgres performance tuning.",
      skills: sk([
        { name: "Python", level: "Advanced", years: 6 },
        { name: "PostgreSQL", level: "Advanced", years: 5 },
        { name: "MongoDB", level: "Intermediate", years: 3 },
        { name: "Docker", level: "Intermediate", years: 4 },
      ]),
      languages: [{ name: "English", proficiency: "Fluent" }, { name: "French", proficiency: "Conversational" }],
      experience: ex([
        {
          company: "Kigali APIs Ltd",
          role: "Backend Engineer",
          start: "2020-05",
          end: "Present",
          desc: "FastAPI services, SQL migrations.",
          tech: ["Python", "PostgreSQL", "Docker"],
          current: true,
        },
      ]),
      education: edu("University of Rwanda", "BSc", "Software Engineering", 2016, 2020),
      projects: [],
      availability: av(),
    },
    {
      firstName: "Zara",
      lastName: "Van der Merwe",
      email: "zara.vdm.umurava.seed@test.local",
      headline: "Frontend Engineer — Vue.js / TailwindCSS",
      location: pick(5),
      bio: "Design collaboration and accessible UI.",
      skills: sk([
        { name: "Vue.js", level: "Advanced", years: 5 },
        { name: "TailwindCSS", level: "Advanced", years: 4 },
        { name: "TypeScript", level: "Intermediate", years: 3 },
      ]),
      languages: [{ name: "English", proficiency: "Fluent" }],
      experience: ex([
        {
          company: "Cape UI Studio",
          role: "Frontend Developer",
          start: "2021-01",
          end: "Present",
          desc: "Vue 3 + Vite apps.",
          tech: ["Vue.js", "TailwindCSS", "TypeScript"],
          current: true,
        },
        {
          company: "Retail Web ZA",
          role: "Web Developer",
          start: "2018-06",
          end: "2020-12",
          desc: "Legacy jQuery to Vue migration.",
          tech: ["Vue.js", "JavaScript"],
          current: false,
        },
      ]),
      education: edu("Stellenbosch University", "BSc", "Computer Science", 2014, 2018),
      projects: [],
      availability: av(),
    },
    {
      firstName: "Samuel",
      lastName: "Owusu",
      email: "samuel.owusu.umurava.seed@test.local",
      headline: "Cloud Engineer — AWS / Docker / CI/CD",
      location: pick(3),
      bio: "Infrastructure as code and deployment pipelines.",
      skills: sk([
        { name: "AWS", level: "Advanced", years: 5 },
        { name: "Docker", level: "Advanced", years: 6 },
        { name: "CI/CD", level: "Advanced", years: 5 },
        { name: "GCP", level: "Intermediate", years: 2 },
      ]),
      languages: [{ name: "English", proficiency: "Fluent" }],
      experience: ex([
        {
          company: "Accra Cloud Co",
          role: "DevOps Engineer",
          start: "2020-02",
          end: "Present",
          desc: "Terraform, GitHub Actions, ECS.",
          tech: ["AWS", "Docker", "CI/CD"],
          current: true,
        },
      ]),
      education: edu("Ashesi University", "BSc", "Computer Science", 2016, 2020),
      certifications: [{ name: "AWS Developer Associate", issuer: "AWS", issueDate: "2021-11" }],
      projects: [],
      availability: av(),
    },
    {
      firstName: "Rania",
      lastName: "Hassan",
      email: "rania.hassan.umurava.seed@test.local",
      headline: "AI Application Engineer — LangChain / Python / Gemini API",
      location: pick(4),
      bio: "Building copilots on top of internal knowledge bases.",
      skills: sk([
        { name: "Python", level: "Advanced", years: 6 },
        { name: "LangChain", level: "Advanced", years: 3 },
        { name: "Gemini API", level: "Advanced", years: 2 },
        { name: "TensorFlow", level: "Intermediate", years: 3 },
      ]),
      languages: [{ name: "English", proficiency: "Fluent" }, { name: "Arabic", proficiency: "Native" }],
      experience: ex([
        {
          company: "Cairo NLP Hub",
          role: "AI Engineer",
          start: "2021-08",
          end: "Present",
          desc: "RAG + evaluation for Arabic/English.",
          tech: ["Python", "LangChain", "Gemini API"],
          current: true,
        },
      ]),
      education: edu("Ain Shams University", "BSc", "Computer Science", 2015, 2019),
      projects: [
        {
          name: "DocQA",
          description: "Internal doc assistant.",
          technologies: ["Python", "LangChain"],
          role: "Lead",
          startDate: "2023-01",
          endDate: "Present",
        },
      ],
      availability: av(),
    },
    {
      firstName: "Brian",
      lastName: "Otieno",
      email: "brian.otieno.umurava.seed@test.local",
      headline: "Software Engineer — React / Node.js / PostgreSQL",
      location: pick(1),
      bio: "Full-stack product delivery for HR-tech.",
      skills: sk([
        { name: "React", level: "Advanced", years: 5 },
        { name: "Node.js", level: "Advanced", years: 5 },
        { name: "PostgreSQL", level: "Intermediate", years: 4 },
        { name: "TypeScript", level: "Advanced", years: 4 },
      ]),
      languages: [{ name: "English", proficiency: "Fluent" }],
      experience: ex([
        {
          company: "Nairobi HR Stack",
          role: "Software Engineer",
          start: "2020-01",
          end: "Present",
          desc: "ATS integrations and reporting.",
          tech: ["React", "Node.js", "PostgreSQL", "TypeScript"],
          current: true,
        },
      ]),
      education: edu("University of Nairobi", "BSc", "Computer Science", 2015, 2019),
      projects: [],
      availability: av(),
    },
    {
      firstName: "Chioma",
      lastName: "Eze",
      email: "chioma.eze.umurava.seed@test.local",
      headline: "Mobile + Web — React Native / Next.js",
      location: pick(2),
      bio: "Cross-platform apps for logistics.",
      skills: sk([
        { name: "React", level: "Advanced", years: 5 },
        { name: "Next.js", level: "Intermediate", years: 3 },
        { name: "TypeScript", level: "Intermediate", years: 3 },
        { name: "TailwindCSS", level: "Intermediate", years: 3 },
      ]),
      languages: [{ name: "English", proficiency: "Fluent" }],
      experience: ex([
        {
          company: "Lagos Logistics App",
          role: "Engineer",
          start: "2021-04",
          end: "Present",
          desc: "React Native fleet app + Next admin.",
          tech: ["React", "Next.js", "TypeScript"],
          current: true,
        },
      ]),
      education: edu("Covenant University", "BSc", "Software Engineering", 2016, 2020),
      projects: [],
      availability: av(),
    },
  ];

/** 5 junior (0–2 yrs) */
export const juniorSeeds = (): TalentSeedProfile[] =>
  [
    {
      firstName: "Leo",
      lastName: "Nkurunziza",
      email: "leo.nkurunziza.umurava.seed@test.local",
      headline: "Junior Full-Stack Developer",
      bio: "Bootcamp + internship; eager to grow.",
      location: pick(0),
      skills: sk([
        { name: "JavaScript", level: "Intermediate", years: 2 },
        { name: "React", level: "Intermediate", years: 1 },
        { name: "Node.js", level: "Beginner", years: 1 },
        { name: "MongoDB", level: "Beginner", years: 1 },
      ]),
      languages: [{ name: "English", proficiency: "Conversational" }],
      experience: ex([
        {
          company: "Kigali Startup Garage",
          role: "Intern → Junior Developer",
          start: "2023-06",
          end: "Present",
          desc: "Bugfixes and small features.",
          tech: ["JavaScript", "React", "MongoDB"],
          current: true,
        },
      ]),
      education: edu("University of Rwanda", "BSc", "Computer Science", 2020, 2024),
      projects: [],
      availability: av(),
    },
    {
      firstName: "Nia",
      lastName: "Wanjiru",
      email: "nia.wanjiru.umurava.seed@test.local",
      headline: "Junior Frontend Developer",
      location: pick(1),
      bio: "University projects in React.",
      skills: sk([
        { name: "React", level: "Intermediate", years: 2 },
        { name: "TailwindCSS", level: "Intermediate", years: 1 },
        { name: "TypeScript", level: "Beginner", years: 1 },
      ]),
      languages: [{ name: "English", proficiency: "Fluent" }],
      experience: ex([
        {
          company: "Nairobi Tech Camp",
          role: "Graduate Trainee",
          start: "2024-01",
          end: "Present",
          desc: "UI components and Storybook.",
          tech: ["React", "TailwindCSS"],
          current: true,
        },
      ]),
      education: edu("University of Nairobi", "BSc", "IT", 2020, 2024),
      projects: [
        {
          name: "Campus Marketplace",
          description: "Final year project.",
          technologies: ["React", "MongoDB"],
          role: "Solo dev",
          startDate: "2023-09",
          endDate: "2024-05",
        },
      ],
      availability: av(),
    },
    {
      firstName: "Ibrahim",
      lastName: "Sarr",
      email: "ibrahim.sarr.umurava.seed@test.local",
      headline: "Junior Backend Developer",
      location: pick(3),
      bio: "SQL and REST coursework.",
      skills: sk([
        { name: "Python", level: "Intermediate", years: 2 },
        { name: "PostgreSQL", level: "Intermediate", years: 1 },
        { name: "Docker", level: "Beginner", years: 1 },
      ]),
      languages: [{ name: "English", proficiency: "Fluent" }, { name: "French", proficiency: "Fluent" }],
      experience: ex([
        {
          company: "Accra Digital Hub",
          role: "Junior Engineer",
          start: "2024-03",
          end: "Present",
          desc: "FastAPI tutorials internal tools.",
          tech: ["Python", "PostgreSQL", "Docker"],
          current: true,
        },
      ]),
      education: edu("University of Ghana", "BSc", "Computer Science", 2020, 2024),
      projects: [],
      availability: av(),
    },
    {
      firstName: "Tariq",
      lastName: "Mostafa",
      email: "tariq.mostafa.umurava.seed@test.local",
      headline: "Graduate Software Engineer",
      location: pick(4),
      bio: "First role out of university.",
      skills: sk([
        { name: "JavaScript", level: "Intermediate", years: 2 },
        { name: "React", level: "Beginner", years: 1 },
        { name: "Node.js", level: "Beginner", years: 1 },
      ]),
      languages: [{ name: "English", proficiency: "Fluent" }, { name: "Arabic", proficiency: "Native" }],
      experience: ex([
        {
          company: "Cairo Junior Dev Shop",
          role: "Junior Developer",
          start: "2024-06",
          end: "Present",
          desc: "Maintenance and tests.",
          tech: ["JavaScript", "React"],
          current: true,
        },
      ]),
      education: edu("Cairo University", "BSc", "Engineering", 2020, 2024),
      projects: [],
      availability: av(),
    },
    {
      firstName: "Sipho",
      lastName: "Nxasana",
      email: "sipho.nxasana.umurava.seed@test.local",
      headline: "Entry-level QA Automator",
      location: pick(5),
      bio: "Playwright scripts and CI smoke tests.",
      skills: sk([
        { name: "JavaScript", level: "Intermediate", years: 2 },
        { name: "TypeScript", level: "Beginner", years: 1 },
        { name: "Docker", level: "Beginner", years: 1 },
      ]),
      languages: [{ name: "English", proficiency: "Fluent" }],
      experience: ex([
        {
          company: "Cape QA Collective",
          role: "QA Engineer",
          start: "2024-02",
          end: "Present",
          desc: "E2E with Playwright.",
          tech: ["JavaScript", "TypeScript", "Docker"],
          current: true,
        },
      ]),
      education: edu("University of Cape Town", "BSc", "Computer Science", 2020, 2024),
      projects: [],
      availability: av(),
    },
  ];

/** 3 wrong-skill profiles — unrelated stacks for typical SWE role */
export const wrongSkillSeeds = (): TalentSeedProfile[] =>
  [
    {
      firstName: "Helena",
      lastName: "Vermeulen",
      email: "helena.vermeulen.umurava.seed@test.local",
      headline: "Executive Pastry Chef — Culinary Arts Specialist",
      bio: "Award-winning pastry programs; zero professional software delivery experience.",
      location: pick(5),
      skills: sk([
        { name: "Culinary Arts", level: "Expert", years: 12 },
        { name: "Menu Planning", level: "Expert", years: 10 },
        { name: "Food Safety HACCP", level: "Advanced", years: 8 },
      ]),
      languages: [{ name: "English", proficiency: "Fluent" }],
      experience: ex([
        {
          company: "Cape Haute Cuisine",
          role: "Executive Pastry Chef",
          start: "2016-03",
          end: "Present",
          desc: "Kitchen leadership and supplier contracts.",
          tech: ["Spreadsheets"],
          current: true,
        },
      ]),
      education: edu("Cape Culinary Institute", "Diploma", "Pastry Arts", 2012, 2014),
      projects: [
        {
          name: "Chocolate Lab Blog",
          description: "Recipe blog — not software.",
          technologies: ["WordPress"],
          role: "Author",
          startDate: "2020-01",
          endDate: "Present",
        },
      ],
      availability: av(),
      socialLinks: { portfolio: "https://example.com/pastry-blog" },
    },
    {
      firstName: "Mohamed",
      lastName: "Farouk",
      email: "mohamed.farouk.umurava.seed@test.local",
      headline: "Agricultural Supply Chain Coordinator",
      bio: "Crop logistics and cold-chain; no programming background.",
      location: pick(4),
      skills: sk([
        { name: "Supply Chain Planning", level: "Advanced", years: 7 },
        { name: "Excel", level: "Advanced", years: 10 },
        { name: "Field Operations", level: "Expert", years: 9 },
      ]),
      languages: [{ name: "Arabic", proficiency: "Native" }, { name: "English", proficiency: "Conversational" }],
      experience: ex([
        {
          company: "Nile Agri Cooperative",
          role: "Coordinator",
          start: "2018-01",
          end: "Present",
          desc: "Route planning for harvest trucks.",
          tech: ["Excel"],
          current: true,
        },
      ]),
      education: edu("Alexandria Faculty of Agriculture", "BSc", "Agronomy", 2012, 2016),
      projects: [],
      availability: av(),
    },
    {
      firstName: "Grace",
      lastName: "Adams",
      email: "grace.adams.umurava.seed@test.local",
      headline: "Corporate Tax Accountant",
      bio: "GAAP-focused accounting; does not ship code.",
      location: pick(3),
      skills: sk([
        { name: "Financial Reporting", level: "Expert", years: 11 },
        { name: "Tax Compliance", level: "Expert", years: 11 },
        { name: "Excel Macros", level: "Intermediate", years: 5 },
      ]),
      languages: [{ name: "English", proficiency: "Fluent" }],
      experience: ex([
        {
          company: "Accra Audit Partners",
          role: "Senior Accountant",
          start: "2015-04",
          end: "Present",
          desc: "Corporate filings and audits.",
          tech: ["Excel"],
          current: true,
        },
      ]),
      education: edu("University of Ghana", "BSc", "Accounting", 2010, 2014),
      certifications: [{ name: "ACCA", issuer: "ACCA", issueDate: "2018-03" }],
      projects: [],
      availability: av(),
      socialLinks: { linkedin: "https://linkedin.com/in/grace-adams-tax" },
    },
  ];

export function allTalentSeedProfiles(): TalentSeedProfile[] {
  return [...seniorSeeds(), ...midSeeds(), ...juniorSeeds(), ...wrongSkillSeeds()];
}
